
-- PostgreSQL port of the MariaDB dump for the gym_oram database
-- Generated 2026-01-25

BEGIN;

SET timezone = 'UTC';
-- Disable FK enforcement during data load to avoid ordering issues
SET session_replication_role = replica;

-- Drop existing views first to avoid dependency issues
DROP VIEW IF EXISTS v_cupo_reservado;
DROP VIEW IF EXISTS v_ocupacion_hoy;
DROP VIEW IF EXISTS v_salas_mas_reservadas;
DROP VIEW IF EXISTS v_suscripciones_ar;
DROP VIEW IF EXISTS v_suscripciones_mensuales;

-- Drop tables if they already exist
DROP TABLE IF EXISTS password_reset_tokens CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS checkin CASCADE;
DROP TABLE IF EXISTS suscripcion_turno CASCADE;
DROP TABLE IF EXISTS suscripcion CASCADE;
DROP TABLE IF EXISTS rutina_plantilla_ejercicio CASCADE;
DROP TABLE IF EXISTS rutina_plantilla CASCADE;
DROP TABLE IF EXISTS ejercicio CASCADE;
DROP TABLE IF EXISTS turno_plantilla CASCADE;
DROP TABLE IF EXISTS sala CASCADE;
DROP TABLE IF EXISTS orden_pago CASCADE;
DROP TABLE IF EXISTS comprobante CASCADE;
DROP TABLE IF EXISTS estado_orden_pago CASCADE;
DROP TABLE IF EXISTS plan CASCADE;
DROP TABLE IF EXISTS socio CASCADE;
DROP TABLE IF EXISTS rol CASCADE;
DROP TABLE IF EXISTS personal CASCADE;
DROP TABLE IF EXISTS avatar CASCADE;
DROP TABLE IF EXISTS grupo_muscular CASCADE;
DROP TABLE IF EXISTS dia_semana CASCADE;

CREATE TABLE dia_semana (
  id smallint PRIMARY KEY,
  nombre varchar(20) NOT NULL
);

CREATE TABLE grupo_muscular (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(80) NOT NULL
);

CREATE TABLE avatar (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url varchar(255) NOT NULL,
  nombre varchar(100),
  es_predeterminado smallint NOT NULL DEFAULT 0 CHECK (es_predeterminado IN (0,1))
);

CREATE TABLE sala (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(80) NOT NULL,
  cupo integer NOT NULL,
  activa smallint NOT NULL DEFAULT 1 CHECK (activa IN (0,1)),
  CONSTRAINT uq_sala_nombre UNIQUE (nombre)
);

CREATE TABLE personal (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(160) NOT NULL,
  telefono varchar(10),
  direccion varchar(100) NOT NULL,
  especialidad varchar(100) NOT NULL,
  estado smallint NOT NULL DEFAULT 1 CHECK (estado IN (0,1)),
  CONSTRAINT uq_personal_telefono UNIQUE (telefono)
);

CREATE TABLE rol (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(50) NOT NULL,
  CONSTRAINT uq_rol_nombre UNIQUE (nombre)
);

CREATE TABLE socio (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dni varchar(32) NOT NULL,
  nombre varchar(160) NOT NULL,
  email varchar(320) NOT NULL,
  telefono varchar(64),
  activo smallint NOT NULL DEFAULT 1 CHECK (activo IN (0,1)),
  creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_nacimiento timestamp without time zone,
  CONSTRAINT uq_socio_dni UNIQUE (dni),
  CONSTRAINT uq_socio_email UNIQUE (email)
);

CREATE TABLE plan (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(80) NOT NULL,
  dias_por_semana integer NOT NULL CHECK (dias_por_semana IN (2,3,5)),
  precio numeric(12,2) NOT NULL,
  activo smallint NOT NULL DEFAULT 1 CHECK (activo IN (0,1)),
  CONSTRAINT uq_plan_nombre UNIQUE (nombre)
);

CREATE TABLE comprobante (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_url text NOT NULL,
  mime_type varchar(100),
  subido_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE estado_orden_pago (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(50) NOT NULL,
  descripcion varchar(255),
  CONSTRAINT uq_estado_orden_pago_nombre UNIQUE (nombre)
);

CREATE TABLE evolucion_fisica (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  socio_id integer NOT NULL,
  fecha date NOT NULL DEFAULT CURRENT_DATE,
  peso numeric(5,2) NOT NULL,
  altura numeric(5,2),
  imc numeric(6,2),
  peso_ideal numeric(6,2),
  pecho numeric(5,2),
  cintura numeric(5,2),
  cadera numeric(5,2),
  brazo numeric(5,2),
  pierna numeric(5,2),
  gemelo numeric(5,2),
  observacion varchar(255)
);

CREATE TABLE orden_pago (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  socio_id integer NOT NULL,
  plan_id integer NOT NULL,
  monto numeric(12,2) NOT NULL,
  vence_en timestamp without time zone NOT NULL,
  estado_id integer NOT NULL DEFAULT 1,
  creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  notas text,
  comprobante_id integer,
  CONSTRAINT uq_orden_pago_socio_plan_creado UNIQUE (socio_id, plan_id, creado_en)
);

CREATE TABLE ejercicio (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(120) NOT NULL,
  tips text,
  media_url text,
  grupo_muscular_id integer
);

CREATE TABLE rutina_plantilla (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(120) NOT NULL,
  objetivo varchar(120),
  imagen_url varchar(255),
  grupo_muscular_id integer
);

CREATE TABLE turno_plantilla (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sala_id integer NOT NULL,
  personal_id integer,
  dia_semana_id smallint NOT NULL,
  hora_inicio time NOT NULL,
  duracion_min integer NOT NULL CHECK (duracion_min BETWEEN 15 AND 240),
  activo smallint NOT NULL DEFAULT 1 CHECK (activo IN (0,1))
);

CREATE TABLE rutina_plantilla_ejercicio (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rutina_id integer NOT NULL,
  ejercicio_id integer NOT NULL,
  orden integer NOT NULL DEFAULT 1,
  series integer,
  repeticiones integer,
  descanso_seg integer,
  CONSTRAINT uq_rutpla_ej UNIQUE (rutina_id, ejercicio_id)
);

CREATE TABLE suscripcion (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  socio_id integer NOT NULL,
  plan_id integer NOT NULL,
  inicio timestamp without time zone NOT NULL,
  fin timestamp without time zone NOT NULL,
  estado smallint NOT NULL DEFAULT 1 CHECK (estado IN (0,1)),
  creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  orden_pago_id integer
);

CREATE TABLE suscripcion_turno (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  suscripcion_id integer NOT NULL,
  turno_plantilla_id integer NOT NULL,
  rutina_id integer,
  CONSTRAINT uq_sus_turno UNIQUE (suscripcion_id, turno_plantilla_id)
);

CREATE TABLE checkin (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  socio_id integer NOT NULL,
  turno_plantilla_id integer,
  profesor_id integer,
  fecha_hora timestamp without time zone NOT NULL,
  observaciones text
);

CREATE TABLE usuario (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(320) NOT NULL,
  alias varchar(100),
  rol_id integer,
  personal_id integer,
  socio_id integer,
  password_hash text NOT NULL,
  estado smallint NOT NULL,
  creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id_avatar integer,
  CONSTRAINT uq_usuario_email UNIQUE (email),
  CONSTRAINT uq_usuario_personal UNIQUE (personal_id),
  CONSTRAINT uq_usuario_avatar UNIQUE (id_avatar)
);

CREATE TABLE password_reset_tokens (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id integer NOT NULL,
  token varchar(255) NOT NULL,
  expira timestamp without time zone NOT NULL
);

-- Foreign keys
ALTER TABLE ejercicio
  ADD CONSTRAINT fk_ejercicio_grupo FOREIGN KEY (grupo_muscular_id) REFERENCES grupo_muscular (id);

ALTER TABLE rutina_plantilla
  ADD CONSTRAINT fk_rutina_grupo FOREIGN KEY (grupo_muscular_id) REFERENCES grupo_muscular (id);

ALTER TABLE orden_pago
  ADD CONSTRAINT fk_orden_plan FOREIGN KEY (plan_id) REFERENCES plan (id),
  ADD CONSTRAINT fk_orden_socio FOREIGN KEY (socio_id) REFERENCES socio (id),
  ADD CONSTRAINT fk_orden_pago_estado FOREIGN KEY (estado_id) REFERENCES estado_orden_pago (id) ON UPDATE CASCADE,
  ADD CONSTRAINT fk_orden_pago_comprobante FOREIGN KEY (comprobante_id) REFERENCES comprobante (id) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE rutina_plantilla_ejercicio
  ADD CONSTRAINT fk_rpe_rutina FOREIGN KEY (rutina_id) REFERENCES rutina_plantilla (id) ON DELETE CASCADE,
  ADD CONSTRAINT fk_rpe_ejercicio FOREIGN KEY (ejercicio_id) REFERENCES ejercicio (id);

ALTER TABLE turno_plantilla
  ADD CONSTRAINT fk_turno_sala FOREIGN KEY (sala_id) REFERENCES sala (id),
  ADD CONSTRAINT fk_turno_profesor FOREIGN KEY (personal_id) REFERENCES personal (id),
  ADD CONSTRAINT fk_dia_semana FOREIGN KEY (dia_semana_id) REFERENCES dia_semana (id) ON UPDATE CASCADE;

ALTER TABLE evolucion_fisica
  ADD CONSTRAINT fk_evolucion_socio FOREIGN KEY (socio_id) REFERENCES socio (id);

ALTER TABLE suscripcion
  ADD CONSTRAINT fk_sus_plan FOREIGN KEY (plan_id) REFERENCES plan (id),
  ADD CONSTRAINT fk_sus_socio FOREIGN KEY (socio_id) REFERENCES socio (id),
  ADD CONSTRAINT fk_suscripcion_orden FOREIGN KEY (orden_pago_id) REFERENCES orden_pago (id);

ALTER TABLE suscripcion_turno
  ADD CONSTRAINT fk_sust_sus FOREIGN KEY (suscripcion_id) REFERENCES suscripcion (id) ON DELETE CASCADE,
  ADD CONSTRAINT fk_sust_turno FOREIGN KEY (turno_plantilla_id) REFERENCES turno_plantilla (id),
  ADD CONSTRAINT fk_rutina_suscripcionturno FOREIGN KEY (rutina_id) REFERENCES rutina_plantilla (id);

ALTER TABLE checkin
  ADD CONSTRAINT fk_check_socio FOREIGN KEY (socio_id) REFERENCES socio (id),
  ADD CONSTRAINT fk_check_turno FOREIGN KEY (turno_plantilla_id) REFERENCES turno_plantilla (id),
  ADD CONSTRAINT fk_checkin_profesor FOREIGN KEY (profesor_id) REFERENCES personal (id) ON DELETE SET NULL;

ALTER TABLE usuario
  ADD CONSTRAINT fk_usuario_rol FOREIGN KEY (rol_id) REFERENCES rol (id) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT fk_usuario_profesor FOREIGN KEY (personal_id) REFERENCES personal (id) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT fk_usuario_socio FOREIGN KEY (socio_id) REFERENCES socio (id) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT fk_usuario_avatar FOREIGN KEY (id_avatar) REFERENCES avatar (id);

ALTER TABLE password_reset_tokens
  ADD CONSTRAINT fk_password_reset_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE CASCADE ON UPDATE CASCADE;

-- Indexes
CREATE INDEX idx_check_socio_fecha ON checkin (socio_id, fecha_hora);
CREATE INDEX idx_check_turno ON checkin (turno_plantilla_id);
CREATE INDEX idx_checkin_profesor ON checkin (profesor_id);
CREATE INDEX idx_orden_socio ON orden_pago (socio_id);
CREATE INDEX idx_orden_plan ON orden_pago (plan_id);
CREATE INDEX idx_orden_estado ON orden_pago (estado_id);
CREATE INDEX idx_orden_comprobante ON orden_pago (comprobante_id);
CREATE INDEX idx_rpe_ejercicio ON rutina_plantilla_ejercicio (ejercicio_id);
CREATE INDEX idx_sus_socio ON suscripcion (socio_id);
CREATE INDEX idx_sus_plan ON suscripcion (plan_id);
CREATE INDEX idx_sus_orden ON suscripcion (orden_pago_id);
CREATE INDEX idx_sust_turno ON suscripcion_turno (turno_plantilla_id);
CREATE INDEX idx_sust_rutina ON suscripcion_turno (rutina_id);
CREATE INDEX idx_evolucion_socio ON evolucion_fisica (socio_id);

-- Data inserts
INSERT INTO avatar (id, url, nombre, es_predeterminado) VALUES
(1, 'uploads/avatar1.png', 'avatar1.png', 1),
(2, 'uploads/avatar2.png', 'avatar2.png', 0),
(3, 'uploads/avatar3.png', 'avatar3.png', 0),
(27, '/uploads/avatars/7b2555f6-52f0-45f0-929e-b2835510934b.jpg', '05a15a2192eed7a1ead4baeee88dad6e', 0),
(28, '/uploads/avatars/728b3c5e-b1c5-4239-abc8-92c86539a6ae.jpg', '468971206_982301963926291_1539331000136656619_n', 0),
(35, '/uploads/avatars/d8d4f4c2-5b56-44ea-9b51-5666875f4fa8.jpg', '469314882_982301983926289_1655566184069659712_n', 0),
(36, '/uploads/avatars/5475863b-c627-4659-ab89-82437a1921a5.jpg', '5475863b-c627-4659-ab89-82437a1921a5.jpg', 0),
(37, '/uploads/avatars/d6588247-4e70-47ec-b19f-353d1d1d6377.jpg', 'd6588247-4e70-47ec-b19f-353d1d1d6377.jpg', 0),
(38, '/uploads/avatars/1de89c86-60fb-44b9-a112-02222628ac46.jpg', '1de89c86-60fb-44b9-a112-02222628ac46.jpg', 0),
(39, '/uploads/avatars/eea1be1f-b70d-4bee-b907-e2b4c7f1fcc3.jpg', 'eea1be1f-b70d-4bee-b907-e2b4c7f1fcc3.jpg', 0),
(40, '/uploads/avatars/679d0056-831e-408d-960c-0ece694dc095.jpg', '679d0056-831e-408d-960c-0ece694dc095.jpg', 0),
(44, '/uploads/avatars/917aac79-5d3b-4237-8e35-eed48511cb81.gif', '398816a082f2c6391f954ec3b2523369', 0),
(45, '/uploads/avatars/05d88338-26fa-4f1a-9325-ae2b7a7db1d8.jpg', '469314882_982301983926289_1655566184069659712_n', 0),
(46, '/uploads/avatars/24fbcba8-f02c-48c6-895a-1ced8086de6b.jpg', '469316400_982301953926292_734471336472164445_n', 0);

INSERT INTO checkin (id, socio_id, turno_plantilla_id, profesor_id, fecha_hora, observaciones) VALUES
(1, 9, 19, NULL, '2025-10-25 16:47:28', NULL),
(2, 24, 51, NULL, '2025-10-27 22:21:20', NULL),
(3, 4, 19, NULL, '2025-11-02 20:18:22', NULL),
(4, 23, 67, NULL, '2025-11-02 20:18:35', NULL),
(5, 11, 45, NULL, '2025-11-07 13:00:00', NULL),
(6, 11, 46, NULL, '2025-11-04 08:00:00', NULL),
(7, 23, 67, NULL, '2025-11-04 15:00:00', NULL),
(8, 24, 33, NULL, '2025-11-03 08:00:00', NULL),
(9, 24, 46, NULL, '2025-11-04 08:00:00', NULL),
(10, 24, 51, NULL, '2025-11-05 08:00:00', NULL),
(11, 24, 56, NULL, '2025-11-06 08:00:00', NULL),
(12, 24, 61, NULL, '2025-11-07 08:00:00', NULL),
(13, 19, 67, NULL, '2025-11-04 15:00:00', NULL),
(14, 25, 67, NULL, '2025-11-04 15:00:00', NULL),
(15, 4, 19, NULL, '2025-11-05 16:00:00', NULL),
(16, 4, 43, NULL, '2025-11-03 18:00:00', NULL),
(17, 4, 57, NULL, '2025-11-06 09:00:00', NULL),
(18, 20, 46, NULL, '2025-11-04 08:00:00', NULL),
(19, 20, 56, NULL, '2025-11-06 08:00:00', NULL),
(20, 18, 67, NULL, '2025-11-04 15:00:00', NULL),
(21, 24, 46, NULL, '2025-11-04 08:00:00', NULL),
(22, 24, 51, NULL, '2025-11-05 08:00:00', NULL),
(23, 24, 63, NULL, '2025-11-07 10:00:00', NULL),
(24, 27, 33, NULL, '2025-11-03 08:00:00', NULL),
(25, 27, 52, NULL, '2025-11-05 09:00:00', NULL),
(26, 4, 57, NULL, '2025-11-05 21:12:57', NULL),
(27, 23, 33, NULL, '2025-11-06 03:47:56', NULL),
(28, 30, 46, NULL, '2025-11-06 03:52:17', NULL),
(29, 8, 19, NULL, '2025-11-05 16:00:00', NULL),
(30, 8, 66, NULL, '2025-11-06 16:00:00', NULL),
(31, 30, 46, NULL, '2025-11-04 08:00:00', NULL),
(32, 30, 56, NULL, '2025-11-06 08:00:00', NULL),
(33, 23, 33, NULL, '2025-11-03 08:00:00', NULL),
(34, 23, 46, NULL, '2025-11-04 08:00:00', NULL),
(35, 23, 51, NULL, '2025-11-05 08:00:00', NULL),
(36, 18, 68, NULL, '2025-11-05 18:00:00', NULL),
(37, 23, 51, NULL, '2025-11-10 01:46:41', 'excelente'),
(38, 11, 45, NULL, '2025-11-14 13:00:00', NULL),
(39, 11, 46, NULL, '2025-11-11 08:00:00', NULL),
(40, 20, 46, NULL, '2025-11-11 08:00:00', NULL),
(41, 20, 56, NULL, '2025-11-13 08:00:00', NULL),
(42, 27, 33, NULL, '2025-11-10 08:00:00', NULL),
(43, 27, 52, NULL, '2025-11-12 09:00:00', NULL),
(44, 8, 19, NULL, '2025-11-12 16:00:00', NULL),
(45, 8, 66, NULL, '2025-11-13 16:00:00', NULL),
(46, 30, 46, NULL, '2025-11-11 08:00:00', NULL),
(47, 30, 56, NULL, '2025-11-13 08:00:00', NULL),
(48, 4, 19, NULL, '2025-11-12 16:00:00', NULL),
(49, 4, 43, NULL, '2025-11-10 18:00:00', NULL),
(50, 4, 57, NULL, '2025-11-13 09:00:00', NULL),
(51, 18, 67, NULL, '2025-11-11 15:00:00', NULL),
(52, 24, 46, NULL, '2025-11-11 08:00:00', NULL),
(53, 24, 51, NULL, '2025-11-12 08:00:00', NULL),
(54, 24, 63, NULL, '2025-11-14 10:00:00', NULL),
(55, 23, 33, NULL, '2025-11-10 08:00:00', NULL),
(56, 23, 46, NULL, '2025-11-11 08:00:00', NULL),
(57, 23, 51, NULL, '2025-11-12 08:00:00', NULL),
(58, 23, 67, NULL, '2025-11-11 15:00:00', NULL),
(59, 24, 33, NULL, '2025-11-10 08:00:00', NULL),
(60, 24, 46, NULL, '2025-11-11 08:00:00', NULL),
(61, 24, 51, NULL, '2025-11-12 08:00:00', NULL),
(62, 24, 56, NULL, '2025-11-13 08:00:00', NULL),
(63, 24, 61, NULL, '2025-11-14 08:00:00', NULL),
(64, 19, 67, NULL, '2025-11-11 15:00:00', NULL),
(65, 25, 67, NULL, '2025-11-11 15:00:00', NULL),
(66, 18, 68, NULL, '2025-11-12 18:00:00', NULL),
(67, 27, 46, NULL, '2025-11-11 18:34:59', 'Buena tecnica sigue asi');

INSERT INTO comprobante (id, file_url, mime_type, subido_en) VALUES
(13, 'uploads/comprobantes/e5c24e2f-d374-4731-a5b6-7eb2d687b9a2.jpg', 'image/jpeg', '2025-10-25 17:36:28'),
(14, 'uploads/comprobantes/5f83f117-9c66-4248-9048-223c765ea56b.jpg', 'image/jpeg', '2025-10-25 17:45:33'),
(15, 'uploads/comprobantes/4aa02b39-f938-4eba-a69d-52144d371cf6.jpg', 'image/jpeg', '2025-10-25 17:47:01'),
(16, 'uploads/comprobantes/5e1a950d-4f83-4045-9b1a-0f2b9fe99e03.jpg', 'image/jpeg', '2025-10-25 17:50:07'),
(17, 'uploads/comprobantes/b6c0f987-e95a-48b0-a1ea-ebfa6290d9b5.jpg', 'image/jpeg', '2025-10-25 18:40:39'),
(18, 'uploads/comprobantes/652b6a60-17e2-4063-ab31-b1155bca8589.jpg', 'image/jpeg', '2025-10-25 18:49:14'),
(19, 'uploads/comprobantes/590ea747-b0c2-4b7d-adf8-a7612713ed06.jpg', 'image/jpeg', '2025-10-25 18:49:53'),
(20, 'uploads/comprobantes/cb14f17a-da34-46d6-8002-6db48dc8c6a0.jpg', 'image/jpeg', '2025-10-25 19:14:44'),
(21, 'uploads/comprobantes/50353fde-03e6-4277-8829-276f72126ef3.jpg', 'image/jpeg', '2025-10-25 19:40:00'),
(22, 'uploads/comprobantes/af18101c-1f78-4ff3-afa9-9eef403a4820.jpg', 'image/jpeg', '2025-10-25 19:44:41'),
(23, 'uploads/comprobantes/7148df4e-1779-4939-8a8f-5a3a9089cb75.jpg', 'image/jpeg', '2025-10-25 19:45:47'),
(24, 'uploads/comprobantes/622ac9f5-791e-41a1-b0d5-f23714eaaeb1.jpg', 'image/jpeg', '2025-10-25 19:49:39'),
(25, 'uploads/comprobantes/86de0ea5-d9bb-475c-b9f9-426046cdb7a5.jpg', 'image/jpeg', '2025-10-25 19:50:34'),
(26, 'uploads/comprobantes/cad0c70d-db82-449d-b849-26beec71d0a6.jpg', 'image/jpeg', '2025-10-25 19:53:31'),
(27, 'uploads/comprobantes/15ac0733-40cc-44d8-8cc3-911c87ffc0b6.pdf', 'application/pdf', '2025-10-25 20:04:42'),
(28, 'uploads/comprobantes/514e72aa-cf2c-4521-aeb3-a769e874ed03.jpg', 'image/jpeg', '2025-10-26 03:20:10'),
(29, 'uploads/comprobantes/7596a098-6f3d-4190-839c-3f6f4aa44683.jpg', 'image/jpeg', '2025-10-30 17:47:40'),
(30, 'uploads/comprobantes/770b76a0-28f7-4eb8-b18e-015ddf7b0c30.jpg', 'image/jpeg', '2025-11-05 15:47:54'),
(31, 'uploads/comprobantes/1bbf1de2-b124-4ec8-98fd-6eaed487e655.jpg', 'image/jpeg', '2025-11-05 16:57:06'),
(32, 'uploads/comprobantes/806ed5ba-195f-4f5a-b0ff-d01011efc430.jpg', 'image/jpeg', '2025-11-05 17:34:41'),
(33, 'uploads/comprobantes/430c4158-a929-4acc-a1a9-d5d5747dac9b.jpg', 'image/jpeg', '2025-11-06 03:45:07'),
(34, 'uploads/comprobantes/127f69d4-7017-46a6-9694-faa71e38b092.jpg', 'image/jpeg', '2025-11-06 03:50:59');

INSERT INTO dia_semana (id, nombre) VALUES
(1, 'Lunes'),
(2, 'Martes'),
(3, 'Miércoles'),
(4, 'Jueves'),
(5, 'Viernes'),
(6, 'Sábado'),
(7, 'Domingo');

INSERT INTO ejercicio (id, nombre, tips, media_url, grupo_muscular_id) VALUES
(1, 'Sentadillas', 'Mantén la espalda recta y baja hasta que los muslos estén paralelos al suelo.', 'Uploads/Ejercicios/58c9294f-75c6-4640-9c84-3a3b844e0e77.png', 6),
(2, 'Prensa de piernas', 'Evita bloquear las rodillas al extender las piernas.', 'Uploads/Ejercicios/cef28f9d-5196-4ba8-9293-fb728298cd79.png', 6),
(3, 'Zancadas', 'Da pasos largos y baja controlando el equilibrio.', 'Uploads/Ejercicios/0637f51d-d4d4-44c0-8f28-c388609a7880.png', 6),
(4, 'Peso muerto rumano', 'Desciende con la espalda recta, sintiendo el estiramiento de los isquiotibiales.', 'Uploads/Ejercicios/c8420a57-8ece-4fab-ab54-7537db6f3862.png', 6),
(5, 'Extensión de piernas', 'No subas demasiado rápido para mantener la tensión muscular.', 'Uploads/Ejercicios/ba3b94e6-d628-488c-b1a0-54dbdecb186a.png', 6),
(6, 'Press de banca plano', 'Alinea la barra con el pecho y controla la bajada.', 'Uploads/Ejercicios/c273df80-2ce1-4398-b4a0-28620009f6bf.png', 5),
(7, 'Press inclinado con mancuernas', 'No choques las mancuernas arriba, controla el movimiento.', 'Uploads/Ejercicios/50a2f201-e51a-4733-9b2f-aab4d5636b2b.png', 5),
(8, 'Aperturas con mancuernas', 'Evita bajar los brazos demasiado para no forzar los hombros.', 'Uploads/Ejercicios/0962b62c-793c-4a27-bf0b-f32b8f041a54.png', 5),
(9, 'Flexiones de brazos', 'Mantén el cuerpo recto y baja hasta casi tocar el suelo.', 'Uploads/Ejercicios/2ab8e978-c6de-4b32-86ed-e1f678d55212.png', 2),
(10, 'Dominadas', 'Evita balancearte, sube controlando el movimiento.', 'Uploads/Ejercicios/a73b7e50-3d40-49fb-b2de-058cbe611b0f.png', 3),
(11, 'Remo con barra', 'Inclina el torso a 45° y lleva la barra hacia el abdomen.', 'Uploads/Ejercicios/98388f1c-5876-437b-8d0c-5f6e732eae16.png', 3),
(12, 'Jalón al pecho', 'No tires con impulso, mantén la espalda recta.', 'Uploads/Ejercicios/99f5096b-7f5b-4136-a3ae-a210d8f2319c.png', 3),
(13, 'Remo en polea baja', 'Lleva la barra al abdomen manteniendo los codos pegados al cuerpo.', 'Uploads/Ejercicios/5f360cce-0385-459f-a1c0-3355fbaca15e.png', 3),
(14, 'Curl de bíceps con barra', 'No muevas los codos, solo los antebrazos.', 'Uploads/Ejercicios/e4afe272-81a7-4e2e-8c80-57263b9355c8.png', 2),
(15, 'Curl de bíceps alternado', 'Gira ligeramente la muñeca al subir.', 'Uploads/Ejercicios/b6a19669-40bc-4ed4-aea7-04b9f24aad6b.png', 2),
(16, 'Extensión de tríceps en polea', 'Evita separar los codos del cuerpo.', 'Uploads/Ejercicios/9bf183fe-466a-4fd6-8e72-95776f298fad.png', 2),
(17, 'Fondos en paralelas', 'Mantén el cuerpo erguido para enfocar el tríceps.', 'Uploads/Ejercicios/aaa7325e-493f-4cdd-8b07-f1bbfa8255a4.png', 2),
(18, 'Press militar', 'Lleva la barra o mancuernas sobre la cabeza sin arquear la espalda.', 'Uploads/Ejercicios/2e64ea5b-1db5-4528-bb7e-dd6c927267f4.png', 4),
(19, 'Elevaciones laterales', 'Levanta los brazos hasta la altura de los hombros.', 'Uploads/Ejercicios/bb86b35e-256e-4b10-855c-a72ded6236c9.png', 4),
(20, 'Elevaciones frontales', 'Evita balancearte, controla el peso al subir y bajar.', 'Uploads/Ejercicios/20957933-2faf-4362-915d-a3e928975cd0.png', 4),
(21, 'Pájaros (posterior)', 'Incliná el torso y levantá los brazos en forma de cruz.', 'Uploads/Ejercicios/15fbb885-60b3-4ab1-8b25-90f2c65fa96b.png', 4),
(22, 'Plancha abdominal', 'Mantén el abdomen contraído y la espalda recta.', 'Uploads/Ejercicios/333b7bc2-1bc2-47e7-a148-b805a28de203.png', 1),
(23, 'Crunch abdominal', 'Evita tirar del cuello, enfócate en el abdomen.', 'Uploads/Ejercicios/19427ab6-c13a-4718-8f61-5e6e315c83a9.png', 3),
(24, 'Elevaciones de piernas', 'Controla el movimiento sin balancearte.', 'Uploads/Ejercicios/a0997484-d121-4956-9ec3-4141040a3c55.png', 6),
(26, 'Burpees', 'Haz el salto y la flexión completa para mayor intensidad.', 'Uploads/Ejercicios/d8ae808d-1731-476e-a100-9587a5103208.png', 1),
(27, 'Salto de cuerda', 'Mantén las rodillas semiflexionadas y ritmo constante.', 'Uploads/Ejercicios/8e46d5ee-1d69-4966-b26b-aac26478779d.png', 1),
(28, 'Escaladores', 'No levantes las caderas demasiado, mantené el core firme.', 'Uploads/Ejercicios/fb53dcb0-8306-4c19-9579-dbab77bad165.png', 1),
(29, 'Sprints', 'Corre distancias cortas al máximo esfuerzo.', 'Uploads/Ejercicios/b1665cce-0fea-479e-962a-7ef2a5f4707f.png', 1),
(31, 'Plancha lateral', 'Apóyate sobre un antebrazo y mantené el cuerpo alineado', NULL, 1);

INSERT INTO estado_orden_pago (id, nombre, descripcion) VALUES
(1, 'Pendiente', 'Orden creada, esperando comprobante'),
(2, 'En revision', 'Comprobante subido, en verificación'),
(3, 'Verificado', 'Pago aprobado y suscripción activada'),
(4, 'Rechazado', 'Comprobante inválido o rechazado'),
(5, 'Expirado', 'Orden vencida sin pago'),
(6, 'Pendiente por error de monto', 'Pago pendiente de verificación'),
(8, 'Pendiente por error ', 'Pago pendiente de verificación');

INSERT INTO evolucion_fisica (id, socio_id, fecha, peso, altura, imc, peso_ideal, pecho, cintura, cadera, brazo, pierna, gemelo, observacion) VALUES
(4, 27, '2025-11-03', 80.00, 175.00, 26.12, 67.38, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(5, 27, '2025-11-03', 82.00, 175.00, 26.78, 67.38, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6, 27, '2025-11-03', 79.00, 170.00, 27.34, 63.58, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO grupo_muscular (id, nombre) VALUES
(1, 'Abdomen'),
(2, 'Brazos'),
(3, 'Espalda'),
(4, 'Hombros'),
(5, 'Pecho'),
(6, 'Piernas'),
(7, 'Full body');

INSERT INTO orden_pago (id, socio_id, plan_id, monto, vence_en, estado_id, creado_en, notas, comprobante_id) VALUES
(8, 6, 3, 20000.00, '2025-10-31 00:00:00', 3, '2025-10-17 17:58:52', NULL, NULL),
(9, 5, 2, 15000.00, '2025-10-31 00:00:00', 3, '2025-10-17 17:59:20', NULL, NULL),
(11, 4, 1, 10000.00, '2025-10-31 00:00:00', 3, '2025-10-17 18:36:51', 'efectivo', NULL),
(12, 9, 1, 10000.00, '2025-10-31 00:00:00', 3, '2025-10-17 18:44:36', 'ef', NULL),
(15, 6, 1, 10000.00, '2025-10-31 00:00:00', 3, '2025-10-17 19:12:24', 'transf', NULL),
(20, 10, 1, 10000.00, '2025-10-31 00:00:00', 3, '2025-10-17 19:21:47', 'trdyt', NULL),
(22, 3, 1, 10000.00, '2025-10-31 00:00:00', 3, '2025-10-17 19:26:45', NULL, NULL),
(26, 11, 1, 10000.00, '2025-10-31 00:00:00', 3, '2025-10-17 20:14:40', NULL, NULL),
(30, 7, 1, 10000.00, '2025-11-06 00:00:00', 3, '2025-10-17 20:48:19', NULL, NULL),
(32, 15, 3, 25000.00, '2025-12-01 00:00:00', 1, '2025-10-20 02:53:57', NULL, NULL),
(33, 18, 3, 25000.00, '2025-12-01 00:00:00', 3, '2025-10-20 03:01:43', NULL, NULL),
(34, 18, 3, 25000.00, '2025-12-01 00:00:00', 1, '2025-10-20 03:05:15', NULL, NULL),
(35, 18, 1, 10000.00, '2025-12-01 00:00:00', 1, '2025-10-20 03:06:12', NULL, NULL),
(36, 18, 1, 10000.00, '2025-12-01 00:00:00', 1, '2025-10-20 03:23:01', NULL, NULL),
(37, 18, 1, 10000.00, '2025-12-01 00:00:00', 1, '2025-10-20 03:45:30', NULL, NULL),
(38, 18, 1, 10000.00, '2025-12-01 00:00:00', 1, '2025-10-20 04:01:23', NULL, NULL),
(39, 18, 3, 25000.00, '2025-12-01 00:00:00', 1, '2025-10-20 04:04:32', NULL, NULL),
(40, 18, 1, 10000.00, '2025-12-01 00:00:00', 3, '2025-10-20 04:12:09', NULL, NULL),
(41, 23, 3, 25000.00, '2025-12-01 00:00:00', 3, '2025-10-25 16:50:34', NULL, NULL),
(43, 20, 3, 25000.00, '2025-12-01 00:00:00', 1, '2025-10-25 17:06:36', NULL, NULL),
(44, 8, 1, 10000.00, '2025-12-01 00:00:00', 3, '2025-10-25 17:09:19', NULL, NULL),
(45, 4, 1, 10000.00, '2025-12-01 00:00:00', 3, '2025-10-25 17:31:41', NULL, NULL),
(46, 25, 3, 25000.00, '2025-12-01 00:00:00', 3, '2025-10-25 17:32:21', NULL, NULL),
(47, 19, 3, 25000.00, '2025-12-01 00:00:00', 3, '2025-10-25 17:34:53', NULL, NULL),
(48, 19, 3, 25000.00, '2025-12-01 00:00:00', 3, '2025-10-25 17:36:28', NULL, 13),
(49, 8, 3, 25000.00, '2025-12-03 00:00:00', 3, '2025-10-25 17:45:33', NULL, 14),
(50, 25, 3, 25000.00, '2025-12-03 00:00:00', 1, '2025-10-25 17:47:01', NULL, 15),
(51, 24, 3, 25000.00, '2025-12-03 00:00:00', 3, '2025-10-25 17:50:07', NULL, 16),
(52, 25, 1, 10000.00, '2025-12-03 00:00:00', 3, '2025-10-25 18:40:39', NULL, 17),
(53, 25, 3, 25000.00, '2025-12-03 00:00:00', 3, '2025-10-25 18:49:13', NULL, 18),
(54, 4, 2, 15000.00, '2025-12-03 00:00:00', 3, '2025-10-25 18:49:53', NULL, 19),
(55, 4, 1, 10000.00, '2025-12-03 00:00:00', 1, '2025-10-25 19:14:44', NULL, 20),
(56, 20, 2, 15000.00, '2025-12-03 00:00:00', 3, '2025-10-25 19:40:00', NULL, 21),
(57, 20, 1, 10000.00, '2025-12-03 00:00:00', 3, '2025-10-25 19:44:41', NULL, 22),
(58, 20, 1, 10000.00, '2025-11-30 00:00:00', 3, '2025-10-25 19:45:47', NULL, 23),
(59, 20, 1, 10000.00, '2025-12-03 00:00:00', 3, '2025-10-25 19:49:39', NULL, 24),
(60, 20, 1, 10000.00, '2025-11-25 00:00:00', 3, '2025-10-25 19:50:34', NULL, 25),
(61, 20, 1, 10000.00, '2025-12-07 00:00:00', 3, '2025-10-25 19:53:31', NULL, 26),
(62, 18, 2, 15000.00, '2025-12-03 00:00:00', 3, '2025-10-25 20:04:42', NULL, 27),
(63, 24, 2, 15000.00, '2025-12-03 00:00:00', 3, '2025-10-26 03:20:10', NULL, 28),
(64, 27, 1, 10000.00, '2025-11-30 17:47:40', 3, '2025-10-30 17:47:40', 'Orden generada por socio desde PlanesSocio', 29),
(65, 17, 2, 15000.00, '2025-12-05 00:00:00', 1, '2025-11-05 15:47:54', NULL, 30),
(66, 29, 2, 15000.00, '2026-01-01 00:00:00', 3, '2025-11-05 16:57:06', NULL, 31),
(67, 12, 1, 10000.00, '2025-12-05 00:00:00', 3, '2025-11-05 17:34:41', 'fvevf', 32),
(68, 23, 2, 15000.00, '2026-01-01 00:00:00', 3, '2025-11-06 03:45:07', NULL, 33),
(69, 30, 1, 10000.00, '2026-01-01 00:00:00', 3, '2025-11-06 03:50:59', NULL, 34),
(70, 27, 2, 15000.00, '2025-12-01 00:00:00', 3, '2025-11-10 22:02:35', NULL, NULL);

INSERT INTO password_reset_tokens (id, usuario_id, token, expira) VALUES
(1, 7, '7fb694be-0021-4097-9141-a3a44f27b9f1', '2025-10-19 17:20:20'),
(2, 7, 'bfd33bcf-60d0-4635-b4fd-b0021d9ed8c5', '2025-10-19 17:29:05'),
(3, 7, '9d478399-fc41-457d-9547-495671cd2cd6', '2025-10-19 17:32:14'),
(4, 7, '772cd18f-3785-4a9f-98e0-837160365efa', '2025-10-19 17:35:28'),
(5, 7, '7ec88995-6e8b-42ac-bb84-0f3b2df80cf7', '2025-10-19 17:40:24');

INSERT INTO personal (id, nombre, telefono, direccion, especialidad, estado) VALUES
(1, 'Virginia Gómez', '2665003432', 'Calle Falsa 123', 'Entrenamiento Funcional', 0),
(11, 'Lourdes Hernández', '2664000002', 'Villa Mercedes', 'Yoga', 1),
(12, 'Matías Rodríguez', '2664000003', 'Merlo', 'Crossfit', 1),
(13, 'Camila Pérez', '2664000004', 'San Luis', 'Pilates', 1),
(14, 'Mariana Gómez', '2665001122', 'Calle Falsa 123', 'Entrenamiento Funcional', 0),
(15, 'Lucía Gómez', '2617896543', 'Mitre 300', 'Crossfit', 0),
(16, 'María Romanela Ricchiardi', '2664750247', '308 Julio a Roca', 'Pilates', 1),
(20, 'Gustavo Diaz', '6666666666', 'Mitre 9876', 'Recepcion', 0),
(22, 'Recepción', '2664000054', 'Recepción', 'Recepción', 1),
(23, 'Administracion', '2664750246', 'Administracion 7876', 'Administracion', 1),
(25, 'Mariana Perez', '2665001133', 'Calle Falsa 123', 'Entrenamiento Funcional', 0),
(27, 'Ana López Andrea', '23452434', 'Avenida Siempreviva 74283', 'Atletismo', 0),
(28, 'Profesor', '233243234', 'Av Siempreviva 345', 'Crossfit', 1);

INSERT INTO plan (id, nombre, dias_por_semana, precio, activo) VALUES
(1, 'Si se puede!', 2, 10000.00, 1),
(2, 'Crossfit Reforzado', 3, 15000.00, 1),
(3, 'Maquina de guerra', 5, 25000.00, 1),
(4, 'Plan Semana Libre', 5, 30000.00, 1);

INSERT INTO rol (id, nombre) VALUES
(1, 'Administrador'),
(5, 'Cliente vip'),
(2, 'Profesor'),
(3, 'Recepción'),
(4, 'Socio');

INSERT INTO rutina_plantilla (id, nombre, objetivo, imagen_url, grupo_muscular_id) VALUES
(1, 'Rutina Full Body', 'Fuerza general', 'Uploads/Rutinas/f040cb3f-a7d6-483b-bb64-39b747740508.png', 7),
(2, 'Fuerza General', 'Desarrollar fuerza global en tren superior e inferior mediante ejercicios compuestos.', 'Uploads/Rutinas/ac64d9d5-5287-4665-8bc7-a8eb5dc263b9.png', 7),
(3, 'Tonificación Completa', 'Mejorar la definición muscular y la resistencia general.', 'Uploads/Rutinas/07365eba-51e1-4b6f-aa7c-fcbf2ecc61a2.png', 7),
(4, 'Hipertrofia Avanzada', 'Incrementar masa muscular con trabajo enfocado en volumen y control de tiempo bajo tensión.', 'Uploads/Rutinas/039d6155-5f0e-47aa-9399-4fc312b7be02.png', 7),
(5, 'Resistencia y Core', 'Fortalecer el abdomen, zona lumbar y estabilidad general del cuerpo.', 'Uploads/Rutinas/c199c804-3653-447c-b12e-1af9f5816522.png', 7),
(6, 'Pérdida de Grasa', 'Rutina de alta intensidad orientada a maximizar el gasto calórico.', 'Uploads/Rutinas/031277a3-95be-4842-970e-7387f23fbca0.png', 7),
(7, 'Glúteos y Piernas', 'Foco en tren inferior: glúteos, femorales y cuádriceps.', 'Uploads/Rutinas/fbfabd4d-b3f6-4b16-81c9-3aba63b8cae1.png', 6),
(8, 'Espalda y Bíceps', 'Rutina dividida para trabajar dorsales y bíceps.', 'Uploads/Rutinas/701128e3-4f79-4240-927d-2c6e524eb4a5.png', 3),
(9, 'Pecho y Tríceps', 'Entrenamiento en empuje con énfasis en fuerza y volumen del tren superior.', 'Uploads/Rutinas/10563486-ce3f-423f-bc81-b9519ec4e1c9.png', 5),
(10, 'Circuito Funcional', 'Ejercicios combinados de fuerza y cardio en intervalos cortos', 'Uploads/Rutinas/773b06df-c6e1-4f2e-b41f-0a6751a3d874.png', 7),
(11, 'Recuperación y Movilidad', 'Sesión ligera enfocada en movilidad articular y flexibilidad.', 'Uploads/Rutinas/44baacc2-7d4b-4829-b63f-4c6289aea100.png', 7),
(13, 'Core básico', 'Fortalecer la zona media y mejorar la estabilidad', 'Uploads/Rutinas/857b5d86-c657-480e-9dcd-1d917d0ce08f.png', 1),
(14, 'Abdomen intenso', 'Definir y tonificar los abdominales superiores e inferiores', 'Uploads/Rutinas/60218d07-93f2-45f2-92d7-2ea7a5ca8641.png', 1),
(15, 'Bíceps y tríceps', 'Aumentar la fuerza y volumen de brazos', 'Uploads/Rutinas/cf034a38-8dcd-4b92-9897-089089edfa47.png', 2),
(16, 'Brazos tonificados', 'Definir los músculos sin ganar volumen excesivo', 'Uploads/Rutinas/87a50db0-2d9f-4ee0-9e39-13bd9e01dd21.png', 2),
(17, 'Espalda ancha', 'Desarrollar la amplitud dorsal y postura', 'Uploads/Rutinas/ae4e6fb1-04e7-4990-b148-ec85f3f84bfe.png', 3),
(18, 'Fortalecer espalda baja', 'Prevenir lesiones y mejorar estabilidad lumbar', 'Uploads/Rutinas/c0c0420c-f911-4742-b60b-f2b116fd68a1.png', 3),
(19, 'Deltoides 360', 'Trabajar todas las cabezas del deltoides', 'Uploads/Rutinas/9fc41bb8-0107-4148-b48e-898ead4c5191.png', 4),
(20, 'Postura y hombros fuertes', 'Fortalecer hombros y trapecios', 'Uploads/Rutinas/1c914e73-4b92-4a74-9277-86dd369305e0.png', 4),
(21, 'Pecho completo', 'Desarrollar masa y fuerza en el pectoral', 'Uploads/Rutinas/9baabe4f-8eff-4577-ae4a-9c1875e47532.png', 5),
(22, 'Definición pectoral', 'Resaltar la parte superior e interna del pecho', 'Uploads/Rutinas/0f1f21c9-b398-4a77-b3bb-7435c9ed3675.png', 5),
(23, 'Piernas potentes', 'Mejorar fuerza y resistencia en tren inferior', 'Uploads/Rutinas/9ae635eb-2f82-4bd8-97f3-7c27bc99c5b8.png', 6),
(24, 'Glúteos y femorales', 'Tonificar y fortalecer glúteos e isquiotibiales', 'Uploads/Rutinas/cd7bb94b-44c8-4e6a-866f-480e5aec8ce9.png', 6);

INSERT INTO rutina_plantilla_ejercicio (id, rutina_id, ejercicio_id, orden, series, repeticiones, descanso_seg) VALUES
(1, 1, 1, 1, 3, 10, 90),
(2, 1, 2, 2, 4, 8, 90),
(3, 1, 3, 3, 3, 12, 60),
(4, 1, 4, 4, 3, 15, 45),
(5, 2, 5, 1, 3, 15, 30),
(6, 2, 6, 2, 3, 20, 30),
(7, 2, 7, 3, 3, 20, 30),
(8, 2, 8, 4, 3, 25, 30),
(9, 3, 9, 1, 5, 10, 75),
(10, 3, 10, 2, 5, 8, 75),
(11, 3, 11, 3, 5, 12, 60),
(12, 3, 12, 4, 4, 10, 90),
(13, 4, 13, 1, 3, 20, 30),
(14, 4, 14, 2, 3, 20, 30),
(15, 4, 15, 3, 4, 25, 20),
(16, 4, 16, 4, 4, 30, 20),
(17, 5, 17, 1, 3, 30, 15),
(18, 5, 18, 2, 3, 25, 15),
(19, 5, 19, 3, 3, 20, 15),
(20, 5, 20, 4, 3, 20, 15),
(21, 6, 21, 1, 4, 12, 60),
(22, 6, 22, 2, 4, 15, 45),
(23, 6, 23, 3, 4, 15, 45),
(24, 6, 24, 4, 4, 20, 45),
(25, 7, 2, 1, 4, 10, 60),
(26, 7, 26, 2, 4, 10, 60),
(27, 7, 27, 3, 4, 12, 45),
(28, 7, 28, 4, 4, 15, 45),
(29, 8, 1, 1, 4, 10, 60),
(30, 8, 2, 2, 4, 10, 60),
(31, 8, 3, 3, 3, 12, 45),
(32, 8, 4, 4, 3, 15, 45),
(33, 9, 5, 1, 3, 20, 20),
(34, 9, 6, 2, 3, 20, 20),
(35, 9, 7, 3, 3, 25, 20),
(36, 9, 8, 4, 3, 30, 15),
(37, 10, 13, 1, 2, 15, 30),
(38, 10, 14, 2, 2, 15, 30),
(39, 10, 15, 3, 2, 15, 30),
(40, 10, 16, 4, 2, 20, 30),
(41, 10, 8, 5, 4, 12, 30),
(46, 6, 4, 5, 4, 20, 30),
(48, 2, 12, 5, 4, 10, 30),
(49, 9, 9, 5, 4, 12, 30),
(50, 13, 22, 1, 4, 12, 60),
(51, 15, 5, 1, 4, 12, 60),
(52, 15, 6, 2, 3, 10, 75),
(55, 14, 18, 1, 3, 12, 60),
(56, 14, 23, 2, 4, 12, 60),
(58, 16, 19, 1, 3, 12, 60),
(59, 11, 21, 1, 3, 12, 60),
(60, 22, 10, 1, 4, 10, 60),
(61, 21, 12, 1, 2, 20, 60),
(62, 19, 19, 1, 3, 12, 60),
(63, 20, 13, 1, 3, 12, 60),
(64, 23, 28, 1, 3, 12, 60),
(65, 24, 1, 1, 3, 12, 60),
(66, 17, 16, 1, 4, 10, 60),
(67, 18, 7, 1, 3, 12, 60);

INSERT INTO sala (id, nombre, cupo, activa) VALUES
(1, 'Sala Principal', 20, 1),
(2, 'Sala Pilates', 4, 1),
(3, 'Sala Spinning', 10, 1);

INSERT INTO socio (id, dni, nombre, email, telefono, activo, creado_en, fecha_nacimiento) VALUES
(1, '30111222', 'Rocío Herrera', 'rocio.herrera@example.com', '+54 261 555-1001', 0, '2025-08-24 20:40:40', NULL),
(2, '32222333', 'Tomás Lucero', 'tomas.lucero@example.com', '+54 261 555-1002', 0, '2025-08-24 20:40:40', NULL),
(3, '33444555', 'Malena Rivas', 'malena.rivas@example.com', '+54 261 555-1003', 1, '2025-08-24 20:40:40', NULL),
(4, '35666777', 'Ariel Quiroga', 'ariel.quiroga@example.com', '+54 261 555-1004', 1, '2025-08-24 20:40:40', NULL),
(5, '37888999', 'Natalia Moyano', 'natalia.moyano@example.com', '+54 261 555-1005', 1, '2025-08-24 20:40:40', NULL),
(6, '40123456', 'Juan Pérez', 'juan.perez@gym.local', '2664001001', 1, '2025-10-10 22:04:48', NULL),
(7, '39234567', 'María López', 'maria.lopez@gym.local', '2664001002', 1, '2025-10-10 22:04:48', NULL),
(8, '38345678', 'Carlos Gómez', 'carlos.gomez@gym.local', '2664001003', 1, '2025-10-10 22:04:48', NULL),
(9, '37456789', 'Laura Fernández', 'laura.fernandez@gym.local', '2664001004', 1, '2025-10-10 22:04:48', NULL),
(10, '36567890', 'Diego Ramírez', 'diego.ramirez@gym.local', '2664001005', 1, '2025-10-10 22:04:48', NULL),
(11, '35678901', 'Lucía Torres', 'lucia.torres@gym.local', '2664001006', 1, '2025-10-10 22:04:48', NULL),
(12, '34789012', 'Nuevo Socio', 'javier.castro@gym.local', '266485516', 1, '2025-10-10 22:04:48', '2015-02-10 00:00:00'),
(13, '33890123', 'Sofía Morales', 'sofia.morales@gym.local', '2664001008', 1, '2025-10-10 22:04:48', NULL),
(14, '32901234', 'Martín Herrera', 'martin.herrera@gym.local', '2664001009', 1, '2025-10-10 22:04:48', NULL),
(15, '31012345', 'Florencia Díaz', 'florencia.diaz@gym.local', '2664001010', 1, '2025-10-10 22:04:48', NULL),
(16, '30123456', 'Pablo Ruiz', 'pablo.ruiz@gym.local', '2664001011', 1, '2025-10-10 22:04:48', NULL),
(17, '29123456', 'Verónica Sánchez', 'veronica.sanchez@gym.local', '2664001012', 1, '2025-10-10 22:04:48', NULL),
(18, '28123456', 'Fernando Castillo', 'fernando.castillo@gym.local', '2664001013', 1, '2025-10-10 22:04:48', NULL),
(19, '27123456', 'Carolina Benítez', 'carolina.benitez@gym.local', '2664001014', 1, '2025-10-10 22:04:48', NULL),
(20, '26123456', 'Andrés Vázquez', 'andres.vazquez@gym.local', '2664001015', 1, '2025-10-10 22:04:48', NULL),
(21, '25123456', 'Valentina Ramos', 'valentina.ramos@gym.local', '2664001016', 1, '2025-10-10 22:04:48', NULL),
(22, '24123456', 'Tomás Navarro', 'tomas.navarro@gym.local', '2664001017', 1, '2025-10-10 22:04:48', NULL),
(23, '23123456', 'Agustina Romero', 'agustina.romero@gym.local', '2664001018', 1, '2025-10-10 22:04:48', NULL),
(24, '22123456', 'Federico Díaz', 'federico.diaz@gym.local', '2664001019', 1, '2025-10-10 22:04:48', NULL),
(25, '21123456', 'Camila Ortiz', 'camila.ortiz@gym.local', '2664001020', 1, '2025-10-10 22:04:48', NULL),
(26, '234234', 'Pedro Mario Villagas', 'MS@hotmail.com', '2665885588', 1, '2025-10-16 23:16:32', NULL),
(27, '65165646', 'Nuevo Socio', 'socio@gym.com', '266485516', 1, '2025-10-28 23:49:01', '2015-02-10 00:00:00'),
(29, '65486552', 'socio nuevo', 'socio123@gym.com', NULL, 1, '2025-10-29 17:07:54', '2008-03-29 00:00:00'),
(30, '23423488', 'Alan Gomes', 'afdsdaf@hotmail.com', '2664854699', 1, '2025-11-06 00:49:17', NULL);

INSERT INTO suscripcion (id, socio_id, plan_id, inicio, fin, estado, creado_en, orden_pago_id) VALUES
(5, 9, 1, '2025-10-17 18:44:36', '2025-11-16 18:44:36', 1, '2025-10-17 18:44:36', 12),
(6, 6, 1, '2025-10-17 19:12:24', '2025-11-16 19:12:24', 1, '2025-10-17 19:12:24', 15),
(7, 10, 1, '2025-10-17 19:21:47', '2025-11-16 19:21:47', 1, '2025-10-17 19:21:47', 20),
(8, 7, 1, '2025-10-17 20:48:19', '2025-11-16 20:48:19', 1, '2025-10-17 20:48:19', 30),
(9, 11, 1, '2025-10-25 17:35:23', '2025-11-24 17:35:23', 1, '2025-10-25 17:35:23', 26),
(10, 5, 2, '2025-10-25 17:35:44', '2025-11-24 17:35:44', 1, '2025-10-25 17:35:44', 9),
(11, 23, 3, '2025-10-25 17:39:59', '2025-11-24 17:39:59', 1, '2025-10-25 17:39:59', 41),
(12, 8, 3, '2025-11-03 00:00:00', '2025-12-03 00:00:00', 1, '2025-10-25 17:45:33', 49),
(13, 24, 3, '2025-11-03 00:00:00', '2025-12-03 00:00:00', 1, '2025-10-25 17:50:07', 51),
(14, 19, 3, '2025-10-25 18:45:30', '2025-11-24 18:45:30', 1, '2025-10-25 18:45:30', 47),
(15, 25, 3, '2025-11-03 00:00:00', '2025-12-03 00:00:00', 1, '2025-10-25 18:49:14', 53),
(16, 4, 2, '2025-11-03 00:00:00', '2025-12-03 00:00:00', 1, '2025-10-25 18:49:53', 54),
(17, 20, 1, '2025-11-07 00:00:00', '2025-12-07 00:00:00', 1, '2025-10-25 19:53:31', 61),
(18, 18, 2, '2025-11-03 00:00:00', '2025-12-03 00:00:00', 1, '2025-10-25 20:04:42', 62),
(19, 24, 2, '2025-11-03 00:00:00', '2025-12-03 00:00:00', 1, '2025-10-26 03:20:10', 63),
(20, 27, 1, '2025-10-30 17:48:31', '2025-11-29 17:48:31', 1, '2025-10-30 17:48:31', 64),
(21, 20, 1, '2025-11-05 16:26:39', '2025-12-05 16:26:39', 1, '2025-11-05 16:26:39', 60),
(22, 7, 1, '2025-11-05 16:27:03', '2025-12-05 16:27:03', 1, '2025-11-05 16:27:03', 30),
(23, 3, 1, '2025-11-05 16:28:45', '2025-12-05 16:28:45', 1, '2025-11-05 16:28:45', 22),
(24, 4, 1, '2025-11-05 16:40:08', '2025-12-05 16:40:08', 1, '2025-11-05 16:40:08', 11),
(25, 25, 3, '2025-11-05 16:44:57', '2025-12-05 16:44:57', 1, '2025-11-05 16:44:57', 46),
(26, 29, 2, '2025-11-05 16:57:59', '2025-12-05 16:57:59', 1, '2025-11-05 16:57:59', 66),
(27, 20, 1, '2025-11-05 17:00:44', '2025-12-05 17:00:44', 1, '2025-11-05 17:00:44', 58),
(28, 8, 1, '2025-11-05 17:01:01', '2025-12-05 17:01:01', 1, '2025-11-05 17:01:01', 44),
(29, 18, 3, '2025-11-05 17:04:40', '2025-12-05 17:04:40', 1, '2025-11-05 17:04:40', 33),
(30, 12, 1, '2025-11-05 00:00:00', '2025-12-05 00:00:00', 1, '2025-11-05 17:34:41', 67),
(31, 23, 2, '2025-12-01 00:00:00', '2025-12-31 00:00:00', 1, '2025-11-06 03:45:07', 68),
(32, 30, 1, '2025-12-01 00:00:00', '2025-12-31 00:00:00', 1, '2025-11-06 03:50:59', 69),
(33, 27, 2, '2025-11-01 00:00:00', '2025-12-01 00:00:00', 1, '2025-11-10 22:02:35', 70);

INSERT INTO suscripcion_turno (id, suscripcion_id, turno_plantilla_id, rutina_id) VALUES
(23, 9, 46, NULL),
(24, 9, 45, NULL),
(25, 19, 46, NULL),
(26, 19, 51, NULL),
(27, 19, 63, NULL),
(28, 17, 46, NULL),
(29, 17, 56, 15),
(30, 13, 33, NULL),
(31, 13, 46, NULL),
(32, 13, 51, NULL),
(33, 13, 56, NULL),
(34, 13, 61, NULL),
(35, 16, 57, NULL),
(36, 16, 43, NULL),
(37, 16, 19, NULL),
(42, 18, 67, NULL),
(43, 15, 67, NULL),
(44, 14, 67, NULL),
(45, 11, 67, 24),
(47, 20, 33, 24),
(52, 20, 52, 10),
(53, 31, 33, 14),
(54, 31, 51, 16),
(56, 32, 46, 1),
(57, 32, 56, NULL),
(58, 31, 46, 22),
(59, 29, 68, NULL),
(60, 28, 66, NULL),
(61, 28, 19, NULL),
(62, 33, 38, 15),
(63, 33, 46, 22),
(64, 33, 18, 3);

INSERT INTO turno_plantilla (id, sala_id, personal_id, dia_semana_id, hora_inicio, duracion_min, activo) VALUES
(1, 1, 1, 1, '19:00:00', 60, 1),
(2, 2, 11, 1, '17:00:00', 60, 1),
(3, 1, 1, 5, '19:00:00', 60, 1),
(4, 1, 1, 2, '19:00:00', 60, 1),
(5, 1, 1, 4, '19:00:00', 60, 1),
(7, 1, 1, 4, '09:00:00', 45, 1),
(10, 1, 1, 4, '08:00:00', 60, 1),
(18, 1, 1, 5, '08:00:00', 60, 1),
(19, 2, 14, 3, '16:00:00', 60, 1),
(33, 1, 11, 1, '08:00:00', 60, 1),
(34, 1, 11, 1, '09:00:00', 60, 1),
(35, 1, 12, 1, '10:00:00', 60, 1),
(36, 1, 12, 1, '11:00:00', 60, 1),
(37, 1, 13, 1, '12:00:00', 60, 1),
(38, 2, 13, 1, '13:00:00', 60, 1),
(39, 1, 11, 1, '14:00:00', 60, 1),
(40, 1, 14, 1, '15:00:00', 60, 1),
(41, 1, 15, 1, '16:00:00', 60, 1),
(42, 1, 15, 1, '17:00:00', 60, 1),
(43, 1, 11, 1, '18:00:00', 60, 1),
(44, 1, 13, 1, '20:00:00', 60, 1),
(45, 2, 15, 5, '13:00:00', 60, 1),
(46, 1, 11, 2, '08:00:00', 60, 1),
(47, 1, 12, 2, '09:00:00', 60, 1),
(48, 1, 13, 2, '10:00:00', 60, 1),
(49, 1, 14, 2, '11:00:00', 60, 1),
(50, 1, 15, 2, '12:00:00', 60, 1),
(51, 1, 11, 3, '08:00:00', 60, 1),
(52, 1, 12, 3, '09:00:00', 60, 1),
(53, 1, 13, 3, '10:00:00', 60, 1),
(54, 1, 14, 3, '11:00:00', 60, 1),
(55, 1, 15, 3, '12:00:00', 60, 1),
(56, 1, 11, 4, '08:00:00', 60, 1),
(57, 1, 12, 4, '09:00:00', 60, 1),
(58, 1, 13, 4, '10:00:00', 60, 1),
(59, 1, 14, 4, '11:00:00', 60, 1),
(60, 1, 15, 4, '12:00:00', 60, 1),
(61, 1, 11, 5, '08:00:00', 60, 1),
(62, 1, 12, 5, '09:00:00', 60, 1),
(63, 1, 13, 5, '10:00:00', 60, 1),
(64, 1, 14, 5, '11:00:00', 60, 1),
(65, 1, 15, 5, '12:00:00', 60, 1),
(66, 2, 14, 4, '16:00:00', 60, 1),
(67, 2, 15, 2, '15:00:00', 60, 1),
(68, 2, 27, 3, '18:00:00', 60, 1);

INSERT INTO usuario (id, email, alias, rol_id, personal_id, socio_id, password_hash, estado, creado_en, id_avatar) VALUES
(7, 'roma.ricchiardi@gmail.com', 'Roma', 1, 16, NULL, '$2a$11$7GOV/Wy8Y2lWfFKitIVNxubuDAbDeIp880jMql5om5U8pmmJD4ETi', 1, '2025-10-18 15:15:59', 27),
(8, 'luli978@gmail.com', 'Luli', 2, 15, NULL, '$2a$11$rRtLmn65sU2w1bz4JGp27.Tim6ljoPYTew2jfWoAAGi5dBFLbGTxq', 0, '2025-10-18 15:16:31', NULL),
(9, 'goyo@gmail.com', 'Goyo', 3, 20, NULL, 'temporal', 1, '2025-10-18 15:17:56', NULL),
(10, 'rece@gym.com', 'Rece', 3, 22, NULL, '$2a$11$Q9u645QepO8B3y4ta.DrD.MjNsJuZvJc3Zw2J9jhxw/CQHsnNODeC', 1, '2025-10-27 22:58:32', 28),
(11, 'admin@gym.com', 'Admin', 1, 23, NULL, '$2a$11$CaVdIg35j00ZDqM0jVCk6urul1expo6n7FKHGXPKxNP/q7T4pPbQW', 1, '2025-10-27 23:34:25', 44),
(12, 'socio@gym.com', 'Socio', 4, NULL, 27, '$2a$11$Ol52YQZkFxriuCSHdS6ayeo9FuhrKUOYYdTYmnAZAofJJp3o9vuyS', 1, '2025-10-28 23:49:07', 45),
(14, 'socio123@gym.com', 'Socio Facha', 4, NULL, 29, '$2a$11$ByG0v9wS3ylFkCDpdl9yh.8FQWKOldde4ycXsr8V.OgRgFhmKFq5W', 1, '2025-10-29 17:08:20', NULL),
(15, 'profe@gym.com', NULL, 2, 28, NULL, 'temporal', 1, '2025-11-11 17:37:24', 46);

-- Views
CREATE OR REPLACE VIEW v_cupo_reservado AS
SELECT
  t.id AS turno_id,
  t.dia_semana_id AS dia_semana_id,
  t.hora_inicio AS hora_inicio,
  count(st.id) AS reservados
FROM turno_plantilla t
LEFT JOIN suscripcion_turno st ON st.turno_plantilla_id = t.id
GROUP BY t.id, t.dia_semana_id, t.hora_inicio;

CREATE OR REPLACE VIEW v_ocupacion_hoy AS
SELECT
  t.id AS turno_id,
  c.fecha_hora::date AS fecha,
  count(c.id) AS asistencias
FROM turno_plantilla t
LEFT JOIN checkin c ON c.turno_plantilla_id = t.id AND c.fecha_hora::date = CURRENT_DATE
GROUP BY t.id, c.fecha_hora::date;

CREATE OR REPLACE VIEW v_salas_mas_reservadas AS
SELECT
  s.nombre AS sala,
  count(st.id) AS reservas
FROM suscripcion_turno st
JOIN turno_plantilla tp ON tp.id = st.turno_plantilla_id
JOIN sala s ON s.id = tp.sala_id
GROUP BY s.nombre
ORDER BY count(st.id) DESC;

CREATE OR REPLACE VIEW v_suscripciones_ar AS
SELECT
  s.id AS id,
  s.socio_id AS socio_id,
  s.plan_id AS plan_id,
  s.inicio AS inicio_ar,
  s.fin AS fin_ar,
  s.estado AS estado
FROM suscripcion AS s;

CREATE OR REPLACE VIEW v_suscripciones_mensuales AS
SELECT
  to_char(suscripcion.inicio, 'YYYY-MM') AS mes,
  count(*) AS cantidad
FROM suscripcion
WHERE suscripcion.estado = 1
GROUP BY to_char(suscripcion.inicio, 'YYYY-MM')
ORDER BY to_char(suscripcion.inicio, 'YYYY-MM') ASC;

-- Align sequences with existing data
SELECT setval('avatar_id_seq', 46, true);
SELECT setval('checkin_id_seq', 67, true);
SELECT setval('comprobante_id_seq', 34, true);
SELECT setval('ejercicio_id_seq', 31, true);
SELECT setval('estado_orden_pago_id_seq', 8, true);
SELECT setval('evolucion_fisica_id_seq', 6, true);
SELECT setval('grupo_muscular_id_seq', 7, true);
SELECT setval('orden_pago_id_seq', 70, true);
SELECT setval('password_reset_tokens_id_seq', 5, true);
SELECT setval('personal_id_seq', 28, true);
SELECT setval('plan_id_seq', 4, true);
SELECT setval('rol_id_seq', 5, true);
SELECT setval('rutina_plantilla_id_seq', 24, true);
SELECT setval('rutina_plantilla_ejercicio_id_seq', 67, true);
SELECT setval('sala_id_seq', 3, true);
SELECT setval('socio_id_seq', 30, true);
SELECT setval('suscripcion_id_seq', 33, true);
SELECT setval('suscripcion_turno_id_seq', 64, true);
SELECT setval('turno_plantilla_id_seq', 68, true);
SELECT setval('usuario_id_seq', 15, true);

-- Re-enable constraints
SET session_replication_role = DEFAULT;

COMMIT;
